version: '3.8'

services:
  otp-server:
    build: .
    container_name: otp_server
    ports:
      - "8080:8080" # Map host port 8080 to container port 8080
    environment:
      # Point to the redis service within the docker network
      REDIS_URL: redis://redis:6379
      # Optional: Override other config values via environment variables if needed
      SERVER_HOST: 0.0.0.0 # Bind to all interfaces within the container
      SERVER_PORT: 8080
      # LOG_LEVEL: debug
    depends_on:
      - redis
    networks:
      - otp-net
    restart: unless-stopped

  redis:
    image: redis:7-alpine # Use a specific alpine version for smaller size
    container_name: otp_redis
    ports:
      - "6379:6379" # Optional: Expose Redis port to host for debugging/external access
    networks:
      - otp-net
    restart: unless-stopped
networks:
  otp-net:
    driver: bridge # Use the default bridge driver
