version: '3.8'

services:
  otp-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      - LOG_LEVEL=debug
      - OTP_LENGTH=6
      - OTP_EXPIRY_SECONDS=30
      - STORAGE_CLEANUP_INTERVAL=60
      - STORAGE_TYPE=redis
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - otp-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - otp-network

networks:
  otp-network:
    driver: bridge

volumes:
  redis-data:
